### ISSUE TITLE
Uncaught HierarchyRequestError: Failed to execute 'appendChild' on 'Node': The new child element ...

### ISSUE THREAD

**Issue by dsandstrom** [rgawenda/atom-move-status-items#5]
I'm getting an error when starting Atom.
1. Move some items around
2. Restart Atom

**Atom Version**: 1.0.0
**System**: Mac OS X 10.10.4
**Thrown From**: [move-status-items](https://github.com/olmokramer/atom-move-status-items) package, v0.0.9
### Stack Trace

Uncaught HierarchyRequestError: Failed to execute 'appendChild' on 'Node': The new child element contains the parent.

```
At /Users/dsandstrom/.atom/packages/move-status-items/lib/move-status-items.js:188

Error: Failed to execute 'appendChild' on 'Node': The new child element contains the parent.
  at Error (native)
  at setInitialOrder (/Users/dsandstrom/.atom/packages/move-status-items/lib/move-status-items.js:176:29)
  at delayedInit (/Users/dsandstrom/.atom/packages/move-status-items/lib/move-status-items.js:38:7)
  at process._tickCallback (node.js:357:13)

```
### Config

``` json
{
  ...
  "move-status-items": {
    "left": [
      "div[is=\"status-bar-file\"]",
      "div[is=\"status-bar-cursor\"]",
      "div[is=\"status-bar-indentation\"]",
      "linter-bottom-tab.linter-tab.active",
      "linter-bottom-tab.linter-tab",
      "linter-bottom-tab.linter-tab",
      "div[is=\"status-bar-selection\"]",
      "div[is=\"space-pen-div\"]"
    ],
    "right": [
      "linter-bottom-status",
      "div[is=\"space-pen-div\"]",
      "div",
      "encoding-selector-status",
      "grammar-selector-status",
      "div.git-view[is=\"status-bar-git\"]"
    ]
  }
}
```

**Comment by olmokramer** [comment]
Hey, thanks for reporting the issue. I'll take a look tomorrow

**Comment by olmokramer** [comment]
Hey, I had some spare time so I looked at this. The mechanism for serializing the HTML elements in the status bar I use doesn't do a very good job at it. The serialization is used to find the items when Atom starts. The settings you see above is the result of the serialization, and as you can see, there's a few duplicates, and even one that's just `"div"`... that matches most of the items in the status bar, and in this case it matches the container, so in the end it tries to append the item container to itself...

I was planning on making a PR for the status-bar package that implements this feature soon, where I will have more control over this process. If I think of a better way to do this before then, I'll implement it. Otherwise this package will be useless anyway :)

**Comment by olmokramer** [comment]
Hey, I found out that I was rejecting a lot of classes in the serialization process, so I removed a lot of them. It should lead to better ordering of the items. You'll have to clear the config after updating, then move everything back in its place. Please let me know if it works better :)

**Comment by dsandstrom** [comment]
I'm still getting the error.  However, I found a workaround (for my case): remove the `"DIV",` from the right array.

**Comment by sbrl** [comment]
Here's another report for you:


1. Install this extension
2. Close atom
3. Open atom

**Atom Version**: 1.1.0
**System**: Ubuntu 15.10
**Thrown From**: [move-status-items](https://github.com/olmokramer/atom-move-status-items) package, v0.0.11


### Stack Trace

Uncaught HierarchyRequestError: Failed to execute 'appendChild' on 'Node': The new child element contains the parent.

```
At /home/sbrl/.atom/packages/move-status-items/lib/move-status-items.js:131

Error: Failed to execute 'appendChild' on 'Node': The new child element contains the parent.
  at Error (native)
  at setInitialOrder (/home/sbrl/.atom/packages/move-status-items/lib/move-status-items.js:157:27)
  at /home/sbrl/.atom/packages/move-status-items/lib/move-status-items.js:29:7
  at doNTCallback0 (node.js:416:9)
  at process._tickCallback (node.js:345:13)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "minimap-codeglance"
    ]
  },
  "move-status-items": {
    "left": [
      "DIV.file-info.buffer-modified[is=\"status-bar-file\"]",
      "DIV.selection-count[is=\"status-bar-selection\"]",
      "LINE-COUNT-STATUS",
      "DIV.cursor-position[is=\"status-bar-cursor\"]",
      "DIV.status-image[is=\"space-pen-div\"]"
    ],
    "right": [
      "A.line-ending-tile",
      "ENCODING-SELECTOR-STATUS.encoding-status",
      "GRAMMAR-SELECTOR-STATUS.grammar-status",
      "DIV.git-view[is=\"status-bar-git\"]",
      "BATTERY-STATUS.battery-status",
      "DIV",
      "DIV.status-bar-clock",
      "DIV.status-bar-clock"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-html-preview, v0.1.13
atom-ternjs, v0.8.4
battery-status, v0.10.3
caniuse, v0.5.5
clock, v1.4.0
devdocs, v0.2.1
external-open, v0.6.1
file-icons, v1.6.11
language-prolog, v0.10.0
line-count-status, v0.0.3
minimap, v4.16.0
minimap-find-and-replace, v4.3.2
minimap-git-diff, v4.1.8
minimap-selection, v4.3.1
move-status-items, v0.0.11
rainbow-extensions, v1.0.4

# Dev
No dev packages
```

Config:

**Comment by scippio** [comment]
Another report:

1. Just run after some items moved and restart

**Atom Version**: 1.4.0-dev-548c85e
**System**: linux 4.2.5-1-ARCH
**Thrown From**: [move-status-items](https://github.com/olmokramer/atom-move-status-items) package, v0.0.11


### Stack Trace

Uncaught HierarchyRequestError: Failed to execute 'appendChild' on 'Node': The new child element contains the parent.

```
At /home/scippio/.atom/packages/move-status-items/lib/move-status-items.js:131

Error: Failed to execute 'appendChild' on 'Node': The new child element contains the parent.
    at Error (native)
    at setInitialOrder (/home/scippio/.atom/packages/move-status-items/lib/move-status-items.js:131:27)
    at /home/scippio/.atom/packages/move-status-items/lib/move-status-items.js:16:7
    at doNTCallback0 (node.js:419:9)
    at process._tickCallback (node.js:348:13)
```

### Config

```json
{
  "core": {
    "projectHome": "/home/scippio/projects",
    "themes": [
      "nucleus-dark-ui",
      "gruvbox"
    ],
    "disabledPackages": [
      "rainbow-extensions",
      "rename-tabs",
      "foldername-tabs",
      "color-tabs-regex",
      "terminal-plus",
      "symbols-view",
      "tree-view-git-branch",
      "minimap-autohide",
      "test-status"
    ],
    "autoHideMenuBar": true,
    "audioBeep": false,
    "packagesWithKeymapsDisabled": [
      "git-control",
      "git-log",
      "tool-bar",
      "minimap",
      "multirow-tabs",
      "git-plus",
      "highlight-line",
      "maximize-panes",
      "atom-ctags",
      "test-status",
      "tab-switcher",
      "move-panes",
      "highlight-selected",
      "wercker-status"
    ],
    "openEmptyEditorOnStart": false
  },
  "move-status-items": {
    "left": [
      "DIV.file-info[is=\"status-bar-file\"]",
      "DIV.cursor-position[is=\"status-bar-cursor\"]",
      "DIV.selection-count[is=\"status-bar-selection\"]",
      "DIV.highlight-selected-status",
      "LINE-COUNT-STATUS",
      "DIV[is=\"space-pen-div\"]",
      "DIV.travis-ci-status[is=\"space-pen-div\"]",
      "DIV"
    ],
    "right": [
      "A.line-ending-tile",
      "ENCODING-SELECTOR-STATUS.encoding-status",
      "GRAMMAR-SELECTOR-STATUS.grammar-status",
      "DIV.git-view[is=\"status-bar-git\"]"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-ctags, v4.4.1
atom-no-tab-close-button, v1.0.0
atom-terminal-panel, v4.4.4
autocomplete-paths, v1.0.2
autocomplete-php, v0.3.7
autohide-tree-view, v0.25.1
color-tabs, v0.1.8
file-icons, v1.6.11
git-log, v0.4.1
gruvbox, v1.0.5
highlight-line, v0.11.0
highlight-selected, v0.11.1
line-count-status, v0.0.3
minimap, v4.16.1
minimap-git-diff, v4.1.8
move-status-items, v0.0.11
nucleus-dark-ui, v0.6.12
pain-split, v1.4.0
pigments, v0.19.0
pretty-json, v0.4.1
scippio-test-status, v0.35.0
symbols-tree-view, v0.10.1
tool-bar, v0.1.9
tool-bar-main, v0.0.8
travis-ci-status, v0.18.0
wercker-status, v1.0.6
```

**Comment by romgrk** [comment]
[Enter steps to reproduce below:]

1. Start Atom
2. Actually, some people might be inserting their own HTMLElements randomly in the statusBar, but it would be good if it could at least not throw.

**Atom Version**: 1.8.0-beta1
**System**: linux 4.5.1-1-ARCH
**Thrown From**: [move-status-items](https://github.com/olmokramer/atom-move-status-items) package, v0.0.11


### Stack Trace

Uncaught HierarchyRequestError: Failed to execute 'appendChild' on 'Node': The new child element contains the parent.

```
At /home/romgrk/.atom/packages/move-status-items/lib/move-status-items.js:131

Error: Failed to execute 'appendChild' on 'Node': The new child element contains the parent.
    at Error (native)
    at setInitialOrder (/home/romgrk/.atom/packages/move-status-items/lib/move-status-items.js:131:27)
    at /home/romgrk/.atom/packages/move-status-items/lib/move-status-items.js:16:7
    at doNTCallback0 (node.js:443:9)
    at process._tickCallback (node.js:372:13)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "audioBeep": false,
    "autoHideMenuBar": true,
    "disabledPackages": [
      "spell-check",
      "symbols-view",
      "news-line",
      "livestyle-atom",
      "editor-stats",
      "autocomplete-ctags",
      "omnisharp-atom",
      "atom-react-native-css",
      "icon-fonts",
      "language-latex",
      "latex",
      "latextools",
      "myth-ui",
      "atom-yeoman",
      "bezier-curve-editor",
      "colors",
      "css-comb",
      "gfm-todotxt",
      "git-control",
      "imdone-atom",
      "markdown-pdf",
      "minimap",
      "minimap-find-and-replace",
      "quick-editor",
      "merge-conflicts",
      "about",
      "autoflow"
    ],
    "ignoredNames": [
      ".git",
      "node_modules",
      "bower_components",
      ".sass_cache"
    ],
    "packagesWithKeymapsDisabled": [
      "imdone-atom",
      "emmet",
      "symbols-tree-view",
      "tool-bar",
      "highlight-line"
    ],
    "themes": [
      "visual-studio-code",
      "gruvbox-syntax"
    ]
  },
  "move-status-items": {
    "left": [
      "DIV.file-info[is=\"status-bar-file\"]",
      "DIV.cursor-position[is=\"status-bar-cursor\"]",
      "DIV.selection-count[is=\"status-bar-selection\"]",
      "DIV.cmdline"
    ],
    "right": [
      "LINTER-BOTTOM-CONTAINER",
      "DIV",
      "ENCODING-SELECTOR-STATUS.encoding-status",
      "GRAMMAR-SELECTOR-STATUS.grammar-status",
      "A.line-ending-tile",
      "SPAN.schema-selector",
      "DIV.git-view[is=\"status-bar-git\"]"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-ctags, v4.5.2
atom-typescript, v8.9.1
atomic-chrome, v0.3.0
autocomplete-clang, v0.9.3
browser-plus, v0.0.60
color-picker, v2.1.1
colorful-json, v1.0.0
cursor-history, v0.5.9
editor-settings, v1.0.4
emmet, v2.4.3
file-icons, v1.7.8
gruvbox-syntax, v2.1.0
highlight-line, v0.11.1
json-schema, v0.1.15
linter, v1.11.4
linter-clang, v3.4.4
local-settings, v0.4.0
move-status-items, v0.0.11
navigate, v0.1.15
package-settings, v1.0.1
pigments, v0.26.0
symbols-tree-view, v0.12.0
tool-bar, v0.4.0
tool-bar-shortcuts, v0.1.5
tree-view-git-branch, v0.1.2
tree-view-git-status, v0.2.3
vim-mode-plus, v0.38.0
vim-mode-plus-move-selected-text, v0.5.0
vim-mode-plus-subword-movement, v0.2.2
visual-studio-code, v0.4.0
you-complete-me, v0.7.4

# Dev
No dev packages
```

**Comment by danielbayley** [comment]
I’m getting this same error.

OS X 10.11.5
Atom 1.8.0
_atom-move-status-items_ 0.0.11

**Comment by piotr-cz** [comment]
Windows 10
Atom 1.12.7
atom-move-status-items 0.0.11

**Comment by sbrl** [comment]
What's the status of a fix for this?
Perhaps a temporary workaround would be a `try....catch` statement that logs uses `console.error`?

Then at least it would stop the error message  from popping up all the time while you work on a proper fix.

Just a suggestion though, take it or leave it 😃

**Comment by rgawenda** [comment]
I've made a simple patch that solved it for me, but I'm quite sure it won't work on all cases.

Open Atom's settings, packages, search move-status-items, enter it, and click the _view code_ button.
Edit lib/move-status-items.js and add:

          if(statusItem.classList == "flexbox-repaint-hack") continue;

at line 131, just after

          if(!isHTMLElement(statusItem)) continue;

**Comment by olmokramer** [comment]
Hi everyone, I'm sorry for the extremely late reply. As you have probably noticed I've stopped maintaining my Atom plugins a few years ago. I got very frustrated with how Atom was maintained and started ignoring all of my plugins. I'm sorry for that. I won't install Atom to test and mergeer PRs, but I'd be happy to transfer my repositories to anyone that wants to maintain any of my plugins. Again, I'm sorry.

**Comment by rgawenda** [comment]
I can try (with this one at least)

**Comment by olmokramer** [comment]
Hi @rgawenda , I've sent a transfer request your way. Good luck!

**Comment by sbrl** [comment]
What's the status of this, @rgawenda? This package is an essential for me (it should be built into the core), and I've been seeing this error message every day for over a year.

**Comment by rgawenda** [comment]
I have to try a fix as this doesn't happen to me lately. Also I'll need to check docs about how to publish to apm registry.

**Comment by sbrl** [comment]
Ah, whatever you did there worked @rgawenda! Thanks to much :D :D :D :cake: :fireworks: :confetti_ball:

I think this long-standing issue can be closed now.
